# -*- coding: utf-8 -*-
"""WebScrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OfkXKTXl9tmVuaobB3M6BbAuQ2MCFPLr

# ***Web Scrapping with BeautifulSoup, requests and html5lib tutorial***

created bt Ankit Raj
# Published on 9 June 2020 created on 5 Jan 2018
# Hope you will get to understand the code.
# Please fell free to update the code.
# The code written below is used for web scrapping ie track on the useful data from any website
# and change it into the structured data for your use.
"""

# importing the lib
from bs4 import BeautifulSoup
import requests
import html5lib

# copy and paste the url on which you want to perform the web scrapping (Ex - flipkart, apple, and many more....)
url = 'https://www.flipkart.com/samsung-galaxy-s20-cloud-blue-128-gb/p/itmce5175ce13e7e?pid=MOBFZXZ2RNFPRFGV&lid=LSTMOBFZXZ2RNFPRFGVVHXAH6&marketplace=FLIPKART&fm=neo%2Fmerchandising&iid=M_68fad91c-4b1e-404b-ab60-acf9f205ec5d_1_1BUWY8OBA8L9_MC.MOBFZXZ2RNFPRFGV&ppt=clp&ppn=samsung-mobile-store&ssid=yy8yg7i2m80000001591638336762&otracker=clp_pmu_v2_Latest%2BSamsung%2Bmobiles%2B_3_1.productCard.PMU_V2_Latest%2BSamsung%2Bmobiles%2B_samsung-mobile-store_MOBFZXZ2RNFPRFGV_neo%2Fmerchandising_2&otracker1=clp_pmu_v2_PINNED_neo%2Fmerchandising_Latest%2BSamsung%2Bmobiles%2B_LIST_productCard_cc_3_NA_view-all&cid=MOBFZXZ2RNFPRFGV'

#getting the requests to  HTML
r = requests.get(url)
content = r.content
print(content)

# html parser with text
r = requests.get(url).text

# here you can see the html code for the website
soup = BeautifulSoup(r, 'html.parser')

print(soup)

# let's prettify the whole code , it allow to understand the code better
print(soup.prettify())

#now extract the data from the html sorce
# HTML tree traversal
title = soup.title
print(title)
print(type(title.string))

title_name = soup.title.name
print(title_name)
print(type(title_name))
# output will show title but the actual info is None

title_string = soup.title.string
print(title_string)

"""# **Commonly Used obj in bs4**
Tag

Navigable String

BeautifulSoup

Comment
"""

title = soup.title

print(type(soup))
print(type(title))
print(type(title.string))

# get the text from html
text = soup.find('p').get_text

print(text)

# get the whole paras
para = soup.find_all('p')
print(para)

# get the anchor tags
tags = soup.find_all('a')
print(tags)

# get the classes
print(soup.find_all('p',class_ = 'lead'))

# get the text 
text = soup.find('p').get_text()
print(text)

print(type(text))

